FROM _DOCKER_BASE_
COPY scripts /hyperledger/baseimage/scripts
RUN cd /hyperledger/baseimage/scripts && \
    common/init.sh && \
    docker/init.sh && \
    common/setup.sh && \
    docker/fixup.sh
ENV GOPATH=/opt/gopath
ENV GOROOT=/opt/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
