FROM _DOCKER_BASE_
COPY scripts /hyperledger/baseimage/scripts
RUN /hyperledger/baseimage/scripts/common/init.sh
RUN /hyperledger/baseimage/scripts/docker/init.sh
RUN /hyperledger/baseimage/scripts/common/setup.sh
ENV GOPATH=/opt/gopath
ENV GOROOT=/opt/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
